name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install UnZip
        run: |
          sudo apt update
          sudo apt install -y unzip
          cat mico.zip.* > mico.zip
          
      - name: Unzip data
        run: |
          cat mico.zip.* > mico.zip
          unzip mico.zip
          ls -lha
                  
      - name: Install Virtualbox
        run: |
          sudo apt update
          sudo apt install -y virtualbox
          sudo vboxmanage import mico.ova --vsys 0 --vmname alp
          sudo vboxmanage showvminfo alp
